name: Build ImmortalWrt

on:
    workflow_dispatch:

env:
    CLONE_COMMAND: git clone -b mt7986 --depth 1 https://github.com/padavanonly/immortalwrtARM
    REPO_NAME: immortalwrtARM

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone from github
              uses: actions/checkout@v3

            - name: Backup config
              run: |
                  mkdir -p backup_config
                  cp .config feeds.conf.default diy.sh backup_config/
                  echo "md5"
                  md5sum .config

            - name: Clone immortalwrtARM repo
              run: |
                  $CLONE_COMMAND
                  cp -rn $REPO_NAME/* .
                  rm -rf $REPO_NAME

            - name: Get the dependency of immortalwrtARM
              run: |
                  chmod +x diy.sh
                  ./diy.sh
                  ./scripts/feeds update -a && ./scripts/feeds install -a

            - name: Recovery from backup
              run: |
                  cp -r -f backup_config/. .
                  echo "md5"
                  md5sum .config

            - name: Upload config before build
              uses: actions/upload-artifact@v3
              with:
                  name: config before build
                  path: .config

            - name: Build immortalwrtARM
              run: |
                  make -j$(nproc) || make -j1 || make -j1 V=99

            - name: Upload build
              uses: actions/upload-artifact@v3
              with:
                  name: ImmortalWrt_build_files
                  path: bin/targets
