name: 测试通道

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'OpenWrt 仓库的拥有者'
        type: string
        required: true
        default: 'padavanonly'
      repo:
        description: 'OpenWrt 仓库的名字'
        type: string
        required: true
        default: 'immortalwrtARM'
      branch:
        description: 'OpenWrt 仓库的分支'
        type: string
        required: true
        default: 'mt7986'
      multithreading:
        description: '开启多线程编译'
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install the software packages required for compilation
        run: |
          sudo apt update
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      - name: Clone current repo
        uses: actions/checkout@v4
        with:
          path: 'current'

      - name: Clone OpenWrt repo
        uses: actions/checkout@v4
        with:
          repository: '${{inputs.owner}}/${{inputs.repo}}'
          path: openwrt

      - run: ls -al

      - name: Copy config
        run: |
          cp -f current/.config current/feeds.conf.default current/diy.sh openwrt/

      - name: Get the dependency of ImmortalWrt
        working-directory: openwrt
        run: |
          chmod +x diy.sh
          ./diy.sh
          ./scripts/feeds update -a && ./scripts/feeds install -a

      - name: Upload config before build
        uses: actions/upload-artifact@v4
        with:
          name: config-before-build
          path: openwrt/.config

      - name: Build ImmortalWrt multithreading
        if: ${{inputs.multithreading == true}}
        working-directory: openwrt
        run: |
          make -j$(nproc)

      - name: Build ImmortalWrt single thread
        if: ${{inputs.multithreading == false}}
        working-directory: openwrt
        run: |
          make -j1 V=99

      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt-build-result
          path: openwrt/bin/targets
